### ISSUE TITLE
Clicking Saved file doen't load it

### ISSUE THREAD

**Issue by doctormo** [aibosan/anigen#2]
Thank you for the very quick previous fix.

When first visiting anigen.org we are given the option of saving the svg. When revisiting the site, the saved file is visible in the list on the load screen. But clicking on it does not load the file. The title bar does change to the filename though, so it's doing something on click.

Browser: Chromium 56

**Comment by aibosan** [comment]
I believe that might have been a bug concerning a phased-out timeline class, which still got called when the clock classes detected the file was looping. Since the method could not be found, it failed to load in the file. It should work now, but let me know if it doesn't, and of any console errors happening if it does.

**Comment by doctormo** [comment]
Confirmed working.
