### ISSUE TITLE
Export did not produce the correct results

### ISSUE THREAD

**Issue by doctormo** [aibosan/anigen#6]
When using the export to png, the results in each png frame were incorrect (very much so!)

![out000](https://cloud.githubusercontent.com/assets/589384/23620461/fc3a02cc-0264-11e7-87be-c50001cb4b04.png)
Compare this frame to this svg file: 
[intro.svg.zip](https://github.com/aibosan/anigen/files/821888/intro.svg.zip)

**Comment by aibosan** [comment]
I could not replicate this problem. You could try resetting the time to 0 and exporting again.

**Comment by doctormo** [comment]
Interesting, once closed, re-opened and set to zero as you say. The problem has gone away. I wonder what it was.

**Comment by aibosan** [comment]
SVG animations are problematic, as they work on various levels. Basically, XML animations (animate element) get written into the XML tree on the fly. But transformations (and motion along path) don't. CSS animations (_also_ the animate element) _also_ don't, but instead of an attribute in DOM, they have to be squeezed out of the browser's "calculated CSS values". Oh, and paths' "d" animations have to be calculated manually because google decided to phase out pathData, because... well... I don't know. They are just kinda stupid, I suppose.

Anyway. Because of this, when exporting, the animations have to be removed one by one, each time using the right approach to push the animated values into the XML tree. When this is done, the XML gets put through a canvas (which can't do most of the animations SVG can) to export the PNG. Since this method is destructive, the original SVG has to be cloned, but because animations might have already been running inside it, some of the XML data might have already been changed. Furthermore, once the XML gets cloned, there's no way to tell what the original values were.

I've been trying to find a solution for this, but each time I do, it breaks another aspect of the whole thing. Obviously, the method used in 0.8.0 isn't ideal either. Just keep this thing in mind if this kind of thing happens in the future, and try to avoid animations with non-zero value at t=0. Those can be an issue. Unless they're not. Like I said, it's a mess.
